/**
 * Revenue math — the single source of truth for the Revenue page.
 *
 * Every projection on the page (calculator, illustrated math blocks, Spotify
 * comparison) runs through these functions. They mirror the splits encoded in
 * the Unis Earnings dashboard code exactly:
 *
 *   Display ad split:  Unis 68% · Supported Artist 15% · L1 10% · L2 5% · L3 2%
 *   Audio ad split:    Artist 60% · Unis 23% · L1 10% · L2 5% · L3 2% (of net after MLC)
 *   Paid tier split:   Artist 50% · Unis 50%
 *   Direct sales:      Artist 85% · Unis 15%
 *
 * All assumptions are labeled as constants and surfaced in the UI disclosure.
 */

export const REVENUE_ASSUMPTIONS = {
  /** Average monthly ad revenue per active user (conservative launch estimate). */
  adRevenuePerActiveUserMonthly: 0.70,

  /** Paid tier price per month. */
  paidTierPrice: 5.99,

  /** MLC compulsory royalty rate on audio ad revenue (2026 CRB Phonorecords IV). */
  mlcRate: 0.153,

  /** Default per-track price if a slider input isn't provided. */
  defaultTrackPrice: 1.99,

  /** Assumed gross per filled pre-roll audio ad (industry average 2025–2026). */
  audioAdGrossPerFill: 0.015,
} as const;

export const SPLITS = {
  display: {
    platform: 0.68,
    supporter: 0.15,
    referralL1: 0.10,
    referralL2: 0.05,
    referralL3: 0.02,
  },
  audioNetOfMlc: {
    artist: 0.60,
    platform: 0.23,
    referralL1: 0.10,
    referralL2: 0.05,
    referralL3: 0.02,
  },
  paidTier: {
    artist: 0.50,
    platform: 0.50,
  },
  directSales: {
    artist: 0.85,
    platform: 0.15,
  },
} as const;

// ── Calculator input shape ──

export type CalculatorInputs = {
  supporters: number;
  /** Fraction 0–1, e.g. 0.4 = 40% of supporters active on any given day. */
  activeDayRate: number;
  /** Fraction 0–1 of supporters who have upgraded to paid tier. */
  paidTierConversion: number;
  referralsL1: number;
  monthlyDirectSales: number;
  directSalePrice: number;
  // Only relevant when audio ads are live:
  monthlyAudioPlays: number;
  /** Fraction 0–1 of plays that include a pre-roll. */
  audioAdFillRate: number;
};

export type CalculatorMode = "at-launch" | "with-audio";

export type StreamBreakdown = {
  /** Monthly $ for display ad supporter share. */
  displaySupporter: number;
  /** Monthly $ for audio ad streaming share (artist's cut on their plays). */
  audioStreaming: number;
  /** Monthly $ for paid tier subscription income. */
  paidTier: number;
  /** Monthly $ for direct sales. */
  directSales: number;
  /** Monthly $ for level-1 referral income. */
  referralL1: number;
  /** Sum of all streams. */
  total: number;
};

// ── Math ──

/**
 * Display-ad supporter income.
 *
 * Each active supporter generates ~$0.70/mo in display ad revenue (assumption).
 * Only "active" supporters (those who open the app) generate revenue — inactive
 * accounts contribute nothing. Artist receives 15% of that.
 *
 * Note: we assume supporters who upgrade to paid tier see no ads, so display
 * revenue from them is zero.
 */
export function displaySupporterIncome(i: CalculatorInputs): number {
  const freeSupporters = i.supporters * (1 - i.paidTierConversion);
  const activeSupporters = freeSupporters * i.activeDayRate;
  const totalAdRev = activeSupporters * REVENUE_ASSUMPTIONS.adRevenuePerActiveUserMonthly;
  return totalAdRev * SPLITS.display.supporter;
}

/**
 * Audio ad streaming income (only when audio tab is active).
 *
 * Monthly plays × fill rate × gross per fill → gross audio ad revenue from
 * the artist's songs. Subtract MLC, then apply 60% artist split.
 */
export function audioStreamingIncome(i: CalculatorInputs): number {
  const filledAds = i.monthlyAudioPlays * i.audioAdFillRate;
  const gross = filledAds * REVENUE_ASSUMPTIONS.audioAdGrossPerFill;
  const net = gross * (1 - REVENUE_ASSUMPTIONS.mlcRate);
  return net * SPLITS.audioNetOfMlc.artist;
}

/**
 * Paid tier subscription income.
 *
 * Every paid supporter contributes $5.99/mo, split 50/50 with Unis.
 */
export function paidTierIncome(i: CalculatorInputs): number {
  const paidSupporters = i.supporters * i.paidTierConversion;
  return paidSupporters * REVENUE_ASSUMPTIONS.paidTierPrice * SPLITS.paidTier.artist;
}

/**
 * Direct sales income.
 * 85% of monthly sale volume.
 */
export function directSalesIncome(i: CalculatorInputs): number {
  return i.monthlyDirectSales * i.directSalePrice * SPLITS.directSales.artist;
}

/**
 * Level-1 referral income.
 * You earn 10% of ad revenue generated by users you directly referred.
 * Assumes same active-day rate as supporters (a reasonable proxy).
 */
export function referralL1Income(i: CalculatorInputs): number {
  const activeReferrals = i.referralsL1 * i.activeDayRate;
  const totalAdRev = activeReferrals * REVENUE_ASSUMPTIONS.adRevenuePerActiveUserMonthly;
  return totalAdRev * SPLITS.display.referralL1;
}

/**
 * Compute the full breakdown for a given input + mode.
 */
export function computeBreakdown(
  inputs: CalculatorInputs,
  mode: CalculatorMode
): StreamBreakdown {
  const displaySupporter = displaySupporterIncome(inputs);
  const audioStreaming = mode === "with-audio" ? audioStreamingIncome(inputs) : 0;
  const paidTier = paidTierIncome(inputs);
  const directSales = directSalesIncome(inputs);
  const referralL1 = referralL1Income(inputs);

  const total =
    displaySupporter + audioStreaming + paidTier + directSales + referralL1;

  return {
    displaySupporter,
    audioStreaming,
    paidTier,
    directSales,
    referralL1,
    total,
  };
}

// ── URL sharing ──

const PARAM_KEYS: Array<keyof CalculatorInputs> = [
  "supporters",
  "activeDayRate",
  "paidTierConversion",
  "referralsL1",
  "monthlyDirectSales",
  "directSalePrice",
  "monthlyAudioPlays",
  "audioAdFillRate",
];

/** Short param-key map so URLs don't get hideous. */
const SHORT_KEYS: Record<keyof CalculatorInputs, string> = {
  supporters: "s",
  activeDayRate: "a",
  paidTierConversion: "p",
  referralsL1: "r",
  monthlyDirectSales: "d",
  directSalePrice: "dp",
  monthlyAudioPlays: "ap",
  audioAdFillRate: "af",
};

const LONG_KEYS: Record<string, keyof CalculatorInputs> = Object.fromEntries(
  Object.entries(SHORT_KEYS).map(([k, v]) => [v, k as keyof CalculatorInputs])
);

export function inputsToQueryString(
  inputs: CalculatorInputs,
  mode: CalculatorMode
): string {
  const params = new URLSearchParams();
  for (const key of PARAM_KEYS) {
    // Round to avoid floating-point garbage in URLs
    const val = Math.round(inputs[key] * 10000) / 10000;
    params.set(SHORT_KEYS[key], String(val));
  }
  params.set("m", mode === "with-audio" ? "a" : "l");
  return params.toString();
}

export function inputsFromQueryString(
  search: string,
  defaults: CalculatorInputs
): { inputs: CalculatorInputs; mode: CalculatorMode } {
  const params = new URLSearchParams(search);
  const inputs: CalculatorInputs = { ...defaults };
  for (const [short, long] of Object.entries(LONG_KEYS)) {
    const raw = params.get(short);
    if (raw !== null) {
      const num = parseFloat(raw);
      if (!Number.isNaN(num)) {
        (inputs as Record<string, number>)[long] = num;
      }
    }
  }
  const modeRaw = params.get("m");
  const mode: CalculatorMode = modeRaw === "a" ? "with-audio" : "at-launch";
  return { inputs, mode };
}

// ── Defaults ──

export const DEFAULT_INPUTS: CalculatorInputs = {
  supporters: 100,
  activeDayRate: 0.40,
  paidTierConversion: 0.08,
  referralsL1: 25,
  monthlyDirectSales: 5,
  directSalePrice: 1.99,
  monthlyAudioPlays: 5000,
  audioAdFillRate: 0.60,
};

// ── Helpers ──

export function formatMoney(n: number): string {
  if (n >= 1000) {
    return `$${n.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
  }
  return `$${n.toFixed(2)}`;
}

export function formatPercent(n: number): string {
  return `${Math.round(n * 100)}%`;
}
